IF DB_ID ('BDCreateDB2') IS NOT NULL
 DROP DATABASE BDCreateDB2;
CREATE DATABASE BDCreateDB2
ON PRIMARY
(NAME = BDCreateDB2_DATA,
FILENAME = 'C:\basedatos\BDCreateDB2_Data.mdf',
SIZE = 3,
FILEGROWTH = 15%)
LOG ON
(NAME= BDCreateDB2_Log,
FILENAME = 'C:\basedatos\BDCreateDB2_Log.ldf',
SIZE = 2MB,
MAXSIZE = 5MB,
FILEGROWTH = 15%)