--ELOY RODAL PÉREZ
USE CATASTRO
USE EMPRESANEW2
GO

--1. Utiliza transacciones implícitas para garantizar que se realiza la operación completa correspondiente al ejercicio 2 y 3 de la tarea 2 de la UD6.
SET IMPLICIT_TRANSACTIONS ON
BEGIN TRANSACTION --O SOLO BEGIN TRAN
BEGIN TRY
SELECT *
FROM CURSO

INSERT INTO CURSO
VALUES ('Diseño web',30)

SELECT *
FROM EDICION

INSERT INTO EDICION
VALUES (
		(SELECT Codigo
		FROM CURSO
		WHERE Nome LIKE ('Diseño web'))
		,
		(SELECT ISNULL(MAX(Numero),0)
		FROM EDICION
		WHERE Codigo=9)+1,'2024-04-15','Pontevedra',
		(SELECT NSSDirector
		FROM DEPARTAMENTO
		WHERE NomeDepartamento LIKE ('Técnico'))
		)
COMMIT TRANSACTION

END TRY
BEGIN CATCH
ROLLBACK TRANSACTION
PRINT 'SE HA PRODUCIDO UN ERROR'
END CATCH

BEGIN TRANSACTION --O SOLO BEGIN TRAN
BEGIN TRY
SELECT *
FROM EDICIONCURSO_EMPREGADO

INSERT INTO EDICIONCURSO_EMPREGADO
SELECT (SELECT codigo
		FROM CURSO
		WHERE Nome LIKE ('Diseño web')),
		(SELECT Numero
		FROM EDICION
		WHERE DATA='2021-04-15'), NSS
FROM EMPREGADO E INNER JOIN DEPARTAMENTO D ON E.NumDepartamentoPertenece=d.NumDepartamento
WHERE NOT EXISTS (SELECT *
				FROM DEPARTAMENTO
				WHERE NSSDirector=NSS)
AND NomeDepartamento LIKE ('Técnico')
COMMIT TRANSACTION

END TRY
BEGIN CATCH
ROLLBACK TRANSACTION --O SOLO ROLLBACK
PRINT 'SE HA PRODUCIDO UN ERROR'
END CATCH
SET IMPLICIT_TRANSACTIONS OFF

--2. Los garajes libres de la calle Zurbarán 101 se venden a precio de saldo, lo que hace que Clementina Ares García, con DNI 32444423M decida comprarlos todos. Actualiza la base de datos para que refleje esta información utilizando transacciones implícitas si fuera necesario

SET IMPLICIT_TRANSACTIONS ON
BEGIN TRANSACTION
BEGIN TRY

INSERT INTO PROPIETARIO
VALUES ('32444423M', 'Clementina', 'Ares', 'García', 'M', NULL)
COMMIT TRANSACTION


END TRY
BEGIN CATCH
ROLLBACK TRANSACTION --O SOLO ROLLBACK
PRINT 'SE HA PRODUCIDO UN ERROR'
END CATCH

SELECT * FROM PROPIETARIO
GO

BEGIN TRANSACTION
BEGIN TRY

UPDATE HUECO
SET DNIPROPIETARIO = '32444423M'
WHERE TIPO = 'GARAJE' AND NUMERO='101' AND CALLE='Zurbarán'
COMMIT TRANSACTION

END TRY
BEGIN CATCH
ROLLBACK TRANSACTION --O SOLO ROLLBACK
PRINT 'SE HA PRODUCIDO UN ERROR'
END CATCH
SET IMPLICIT_TRANSACTIONS OFF

SELECT * FROM HUECO

--3. Se crea una nueva sede para el departamento Técnico en Villagarcía.
SET IMPLICIT_TRANSACTIONS ON
BEGIN TRANSACTION
BEGIN TRY

INSERT INTO LUGAR
VALUES((SELECT MAX(ID) + 1 
		FROM LUGAR), 3, 'Villagarcía')
COMMIT TRANSACTION

END TRY
BEGIN CATCH
ROLLBACK TRANSACTION --O SOLO ROLLBACK
PRINT 'SE HA PRODUCIDO UN ERROR'
END CATCH
SET IMPLICIT_TRANSACTIONS OFF

SELECT * FROM LUGAR

--4. El empleado de nombre Paulo Máximo Guerra se cambia de sexo y pasa a llamarse Mónica. Actualiza la base de datos.
SET IMPLICIT_TRANSACTIONS ON
BEGIN TRANSACTION
BEGIN TRY

UPDATE EMPREGADO
SET Nome = 'Mónica', Sexo = 'M'
WHERE Nome = 'Paulo' AND Apelido1 = 'Máximo' AND Apelido2 = 'Guerra'
COMMIT TRANSACTION

END TRY
BEGIN CATCH
ROLLBACK TRANSACTION --O SOLO ROLLBACK
PRINT 'SE HA PRODUCIDO UN ERROR'
END CATCH
SET IMPLICIT_TRANSACTIONS OFF

SELECT * FROM EMPREGADO

--5. Utiliza transacciones explícitas para garantizar que se realiza la operación completa correspondiente al ejercicio 5 de la tarea 2 de la UD6.
BEGIN TRANSACTION
BEGIN TRY

UPDATE EMPREGADO_PROXECTO
SET NumProxecto=(SELECT NumProxecto
					FROM PROXECTO P
					WHERE P.NomeProxecto='XESTION DA CALIDADE')
WHERE NSSEmpregado='9900000'
AND NumProxecto=(SELECT NumProxecto
				 FROM PROXECTO
				 WHERE NomeProxecto='Portal');
COMMIT TRANSACTION


END TRY
BEGIN CATCH
ROLLBACK TRANSACTION --O SOLO ROLLBACK
PRINT 'SE HA PRODUCIDO UN ERROR'
END CATCH

SELECT *
FROM EMPREGADO_PROXECTO
WHERE NSSEmpregado=9900000