--ELOY RODAL PÉREZ

--1.

SELECT NOMBREZONA, DESCRIPCIÓN, OBSERVACIONES
FROM ZONAURBANA;

--2.

SELECT CALLE, NUMERO, NUMPLANTAS
FROM CASAPARTICULAR;

--3. Entendiendo vivienda unifamiliar como "CASAPARTICULAR".

SELECT CALLE, NUMERO, METROSCONSTRUIDOS
FROM CASAPARTICULAR
WHERE PISCINA = 'S';

--4. Entendiendo vivienda unifamiliar como "VIVIENDA".

SELECT CALLE, NUMERO, METROSSOLAR
FROM VIVIENDA;

--5.

SELECT *
FROM PISO
WHERE NUMHABITACIONES = '3';

--6.

SELECT CALLE, NUMERO, METROSSOLAR
FROM VIVIENDA
WHERE METROSSOLAR > 190 AND METROSSOLAR < 300;

--7.

SELECT CALLE, NUMERO
FROM BLOQUEPISOS
WHERE NUMPISOS > 15
ORDER BY CALLE, NUMERO;

--8.

SELECT CALLE, NUMERO, METROSSOLAR, NOMBREZONA
FROM VIVIENDA
WHERE NOMBREZONA = 'Centro';

--9.

SELECT DNI, NOMBRE, APELLIDO1, APELLIDO2
FROM PROPIETARIO
WHERE APELLIDO1 = 'López'
ORDER BY APELLIDO1, APELLIDO2, NOMBRE;

--10.

SELECT CALLE, NUMERO, METROSSOLAR
FROM VIVIENDA
WHERE TIPOVIVIENDA = 'Bloque' AND METROSSOLAR > 450;
 
--11.

SELECT HUECO.CALLE, HUECO.NUMERO, HUECO.ID_HUECO, HUECO.TIPO
FROM HUECO 
WHERE TIPO = 'GARAJE';

--12.

SELECT NOMBREZONA, DESCRIPCIÓN
FROM ZONAURBANA
WHERE NUMPARQUES > 1
ORDER BY NUMPARQUES DESC, NOMBREZONA ASC ;

--13.

SELECT NOMBREZONA, DESCRIPCIÓN, NUMPARQUES, OBSERVACIONES
FROM ZONAURBANA
WHERE OBSERVACIONES is NOT NULL;
--14.

SELECT DNI, NOMBRE, APELLIDO1, APELLIDO2
FROM PROPIETARIO
WHERE LEN(NOMBRE) = 3
ORDER BY APELLIDO1, APELLIDO2, NOMBRE;

--15.
SELECT DISTINCT PISO.CALLE, NUMERO, PLANTA, PUERTA, METROSUTILES, METROSCONSTRUIDOS, METROSCONSTRUIDOS - METROSUTILES AS DIFERENCIA
FROM PISO
ORDER BY DIFERENCIA DESC;

--16.

SELECT CALLE, NUMERO, PLANTA, PUERTA, NUMHABITACIONES, METROSUTILES, METROSCONSTRUIDOS, DNIPROPIETARIO
FROM PISO
WHERE NUMHABITACIONES IN (1, 3, 5, 6);

--17.

SELECT CALLE, NUMERO, PLANTA, PUERTA, NUMHABITACIONES, METROSUTILES, METROSCONSTRUIDOS, DNIPROPIETARIO, METROSCONSTRUIDOS - METROSUTILES AS DIFERENCIA
FROM PISO
WHERE NUMHABITACIONES IN (1, 3, 5, 6) AND (METROSCONSTRUIDOS > (METROSUTILES + 10));

--18.

SELECT NOMBREZONA, NUMPARQUES
FROM ZONAURBANA
WHERE NUMPARQUES < 3 AND OBSERVACIONES is NULL;

--19.

SELECT CALLE, NUMERO, PLANTA, PUERTA, NUMHABITACIONES, METROSUTILES, METROSCONSTRUIDOS, DNIPROPIETARIO
FROM PISO
WHERE NUMHABITACIONES = 2 AND LEFT(CALLE, 1) = 'L' AND METROSUTILES < 100;

--20.
SELECT NOMBREZONA
FROM VIVIENDA
WHERE TIPOVIVIENDA = 'Casa'
ORDER BY NOMBREZONA DESC